---

ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_user: admin
ansible_password: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: cisco

ios_inv_tmp_j2: /home/n9kway/ansible/templates/Reports/inventory_report.j2
dst_path: /home/n9kway/ansible/results/html/inventory_report.html
backup_path: "~/ansible/backup/runnning_config_{{inventory_hostname }}.cfg"
config: show running-config
# nodes:
#   r1: 
#    Loopback300: '192.168.10.3'
#   r2:
#     Loopback300: '192.168.20.3'

hostname: show run | in hostname
interfaces_info: show ip int brief
ipv6_interface_info: show ipv6 int br
clock: show clock
arp: show arp
run_command: show run
ntp_config: ntp server 192.168.60.10
l3_config: interface loopback500
