---

ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_user: admin
ansible_password: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: cisco


interfaces: show ip int brief
run_command: show run | i hostname
