---

- name: Run cfg commands on routers
  hosts: routers

  tasks:

    - name: Config line vty
      ios_config:
        parents:
          - line vty 0 4
        commands:
          #- login local
          - transport input ssh

