---

- name: Run cfg commands on routers
  hosts: routers

  tasks:

    - name: Config line vty
      ios_config:
        parents:
          - line vty 0 4
        lines:
          - exec-timeout 100 0
      register: cfg
      

    - name: Show config updates
      debug: var=cfg.updates
      when: cfg.changed
