---
- name: Run config on routers
  hosts: routers

  tasks: 

    - name: Create a new user
      cisco.ios.ios_user:
        name: n9kway
        privilege: 15
        configured_password: cisco
        state: present
    - name: Save config


