---

- name: Collect IOS facts
  hosts: routers

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: min
        gather_network_resources:
          - interfaces
          - l3_interfaces
    - name: Copy facts to files
      copy:
        content: "{{ansible_network_resources.l3_interfaces[-1] | to_nice_json }}"
        dest: "{{ l3_interfaces }}"

