---

- 
  name: Run show commands on routers
  hosts: routers
  gather_facts: false

  # vars from ansible/group_vars/all.yml

  tasks:

    - name: Run show commands
      ios_command:
        commands:
          - "{{ hostname }}" 
          - "{{ arp }}"
          - "{{ interfaces_info }}"
          - "{{ clock }}"
      register: result

    - name: Debug Hostnames
      debug: var=result.stdout_lines[0]

    - name: Debug Show ARP
      debug: var=result.stdout_lines[1]

    - name: Debug Show Interface Brief
      debug: var=result.stdout_lines[2]

    - name: Debug Show Clock
      debug: var=result.stdout_lines[3]
