---
- 
  name: Sending Basic IOS Commands
  hosts: routers
  gather_facts: no

  tasks:

    - name: Configuring Loopback99 On Selected Devices
      cisco.ios.ios_command:
        commands: 
          - configure terminal
          - interface loopback100
          - description Created-By-Ansible
          - end


    - name: Verifying Loopback100
      cisco.ios.ios_command:
        commands: show run interface loopback100
      register: loopback100

    - debug: var=loopback100.stdout_lines


