
---

- name: Run show commands on routers
  hosts: routers
  gather_facts: false

  tasks:

    - name: run sh ip int br
      ios_command:
        commands: "{{interfaces}}"

    - name: run sh ip arp
      ios_command:
        commands: sh ip arp


