---

 - name: configure network devices
   hosts: r4, r3
   gather_facts: false
   
   tasks: 
     
     - name: configure device with config
       cli_config:
         config:
           src: "{{ interface_config }}"
