---

 - name: Generating an HTML report
   hosts: routers
   gather_facts: false

   tasks:

     - name: Gathering ios facts
       ios_facts:
         gather_subset: all

     - name: Create HTML report
       template:
         src: "{{ inventory_template }}"
         dest: "{{ inventory_report }}"
       delegate_to: localhost 
       run_once: true

 
