---
- 
  name: Backup Configs
  hosts: all
  gather_facts: no

  tasks:
    
    - name: Generate Backup Configs
      cisco.ios.ios_config:
        backup: yes
      register: config_output

    - name: Shorten The Name Of The Backup File
      copy:
        src: "{{config_output.backup_path}}"
        dest: "./backup/{{inventory_hostname}}.config"

    - name: Remove Non Config Lines
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        line: "Building configuration..."
        state: absent
     
    - name: Remove Non Config Lines - REGEXP
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        regexp: "Current configuration.*"
        state: absent

    - name: Remove Non Config Lines - REGEXP
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        regexp: "! Last configuration change.*"
        state: absent





