---
- 
  name: Restoring Backup Configs
  hosts: all
  gather_facts: no

  tasks:

    - name: Ensuring SCP Is Configured
      cisco.ios.ios_command:
        commands: 
          - configure terminal
          - ip scp server enable
          - username keithbogart privilege 15 password cisco
##  The username in the command above should be changed to your local machine's username ##
          - end

    - name: Restoring Golden Config
      command: scp ./backup/{{inventory_hostname}}.config {{inventory_hostname}}:/{{inventory_hostname}}.config

    - name: Reverting To Golden Config
      cisco.ios.ios_command:
        commands: config replace flash:{{inventory_hostname}}.config force 
