---

- name: Collect IOS facts
  hosts: 192.168.60.11

  vars: 
    l3_intf: "{{ lookup('file', '~/ansible/output/192.168.60.11_l3_intf.json/') | from_json}}"

  tasks: 

    - name: Read data from file
      ios_l3_interfaces:
        config: "{{ l3_intf }}"
        state: deleted
      register: result
    

    - name: Show result
      debug: var=result.commands 
