---

- name: Run cfg commands on router
  hosts: routers

  tasks:

    - name: Gather facts 
      ios_facts:
        gather_subset: interfaces

    - name: Config OSPF
      ios_config:
        src: templates/ospf_facts.j2
