---
- 
  name: Backup Configs
  hosts: routers
  gather_facts: true


  tasks:
    
    - name: Show running-configuration
      ios_command:
        commands: "{{ config }}"
      register: config

    - name: save running config to ~/ansible/backup
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_path }}" 
