---

 - name: configure network devices
   hosts: r1, r2
   gather_facts: false
   
   tasks: 
     
     - name: configure device with config
       cli_config:
         config: "{{lookup('template', '~/ansible/templates/intf_template.j2')}}"
