---
- 
  name: Backup Configs
  hosts: routers
  gather_facts: no

  tasks:
    
    - name: Generate Backup Configs
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: /home/n9kway/ansible/yaml_files/backup/
          filename: "{{inventory_hostname}}-backup.config"
