---
- 
  name: Scanning For Configuration Changes
  hosts: routers
  gather_facts: no

  tasks:


    - name: Perform Config Diff Against Master Config
      cisco.ios.ios_config:
        diff_against: intended
        intended_config: "{{ lookup('file', './yaml_files/backup/{{inventory_hostname}}_backup.config') }}"
