net_hostname: IPN3
net_interfaces:
    loopback0:
      ipv4:
          address: 13.13.13.13
          masklen: '32'
    Ethernet1/1:
        description: IPN3 <--> IPN1
        ipv4:
            address: 10.21.1.3
            masklen: '29'
    Ethernet1/2:
        description: IPN3 <--> R2
        ipv4:
          address: 10.23.1.3
          masklen: '29'
    Ethernet1/3:
        description: IPN3 <--> IPN4
        ipv4: 
            address: 10.21.6.3
            masklen: '29' 
    Ethernet1/4:
        description: IPN3 <--> R4 
        ipv4:
            address: 10.23.2.3
            masklen: '29'
    Ethernet1/5:
        description: IPN3 <--> IPN2
        ipv4: 
            address: 10.21.3.3
            masklen: '29'

