---

hostname: r1
loopback_id: 0
loopback_ip: 1.1.1.1
ospf_area_0:
  - 10.1.1.0
  - 10.1.1.4
  - 10.1.1.8
eth1: GigabitEthernet 1
eth2: GigabitEthernet 2
eth3: GigabitEthernet 3
eth4: GigabitEthernet 4
eth1_ip: 10.1.1.5
eth2_ip: 10.1.1.9
eth4_ip: 10.1.1.1
mask_30: 255.255.255.252

