---

- name: Collect IOS facts
  hosts: 192.168.60.11


  tasks: 

    - name: configure vlans
      ios_vlans:
        config: 
          - name: test_Absible
            vlan_id: 100
          - name: test1_Ansible
            vlan_id: 110  
        state: merged
      register: result
    
    - name: Show ansible_network_resources
      debug: var=result.commands
